language: node_js

node_js:
- node

sudo: required

stages:
  - test
  - name: build
    if: tag IS present && branch = master
    # if: branch = master
  - name: buildInsider
    if: tag IS present && branch = develop
    # if: branch = develop


jobs:
  include:
  # Test stage
  - stage: test
    install:
    - npm ci
    script:
    - npm test
  
  # Normal build stage
  - stage: build
    name: Build Win
    os: windows
    install:
    - ./.travis/InstallWin.bat
    script:
    - npm run release:win

  - name: Build Linux
    os: linux
    install:
    - sh ./.travis/InstallLinux.sh
    script:
    - npm run release:linux

  - name: Build Mac
    os: osx
    install:
    - sh ./.travis/InstallMac.sh
    script:
    - npm run release:osx

  # Insider build stage
  - stage: buildInsider
    name: Build Win
    os: windows
    install:
    - ./.travis/InstallWin.bat
    script:
    - npm run prerelease:win

  - name: Build Linux
    os: linux
    install:
    - sh ./.travis/InstallLinux.sh
    script:
    - npm run prerelease:linux

  - name: Build Mac
    os: osx
    install:
    - sh ./.travis/InstallMac.sh
    script:
    - npm run prerelease:osx
    
