language: node_js

node_js:
- node

sudo: required

stages:
  - Test
  - name: Build
    if: tag ~= /^v\d+\.\d+\.\d+$/
    # if: branch = master
  - name: Build Insider
    if: tag ~= /^v\d+\.\d+\.\d+\-\w+\.\d+$/
    # if: branch = develop

jobs:
  include:
  # Test stage
  - stage: Test
    os: linux
    install:
      - sh ./.travis/InstallLinux.sh
    script:
      - npm run ci:copyschemes
      - sh ./.travis/DebugFiles.sh
      - npm test
      - npm run lint

  # Normal build stage
  - stage: Build
    name: Build Windows
    os: windows
    install:
      - ./.travis/InstallWin.bat
    script:
      - npm run compile
      - npm run release:win

  - name: Build Linux
    os: linux
    install:
      - sh ./.travis/InstallLinux.sh
    script:
      - npm run compile
      - npm run release:linux

  - name: Build OSX
    os: osx
    osx_image: xcode11.2
    install:
      - sh ./.travis/InstallMac.sh
    script:
      - npm run compile
      - npm run release:osx

  # Insider build stage
  - stage: Build Insider
    name: Build Windows Insider
    os: windows
    install:
      - ./.travis/InstallWin.bat
    script:
      - npm run compile
      - npm run prerelease:win

  - name: Build Linux Insider
    os: linux
    install:
      - sh ./.travis/InstallLinux.sh
    script:
      - npm run compile
      - npm run prerelease:linux

  - name: Build OSX Insider
    os: osx
    osx_image: xcode11.2
    install:
      - sh ./.travis/InstallMac.sh
    script:
      - npm run compile
      - npm run prerelease:osx
